//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlexusInventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Supplier_ID { get; set; }
        public string Supplier_Name { get; set; }
        public string Supplier_Address { get; set; }
        public Nullable<short> Phone { get; set; }
    }
}
